version: '3.8'
services: 
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iloveyou044
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fast-api
    ports: 
      - 5000:15400
    volumes: 
      - ./api:/api
      - ./upload-images/:/upload-images/user/
    env_file: 
      - ./api/.env
    depends_on:
      - postgres

volumes:
  postgres_data: